[package]
name = "x-aho-corasick"
version = "0.5.1"
edition = "2024"
authors = ["hardglitch"]

[lints.clippy]
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
#indexing_slicing = "warn"
#arithmetic_side_effects = "warn"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
daachorse = "5.0.0"
aho-corasick = "1.1.5"

[[bench]]
name = "bench_proof"
harness = false

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "bench_ol"
harness = false

[[bench]]
name = "bench_hardcore"
harness = false

[[bench]]
name = "bench_hardcore_ol"
harness = false

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "*", features = ["derive"], optional = true }
